name: webpush_encryption
description: HTTP-ECE decryption for WebPush content based on RFC 8291.
version: 1.0.0
homepage: https://codeberg.org/UnifiedPush/dart-webpush-encryption
repository: https://codeberg.org/UnifiedPush/dart-webpush-encryption
issue_tracker: https://codeberg.org/UnifiedPush/dart-webpush-encryption/issues

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
   webcrypto: ^0.5.7

dev_dependencies:
  lints: ^4.0.0
