name: webpush_encryption
description: HTTP-ECE decryption for WebPush content based on RFC 8291.
version: 0.1.0
homepage: https://codeberg.org/UnifiedPush/dart-webpush-encryption
repository: https://codeberg.org/UnifiedPush/dart-webpush-encryption
issue_tracker: https://codeberg.org/UnifiedPush/dart-webpush-encryption/issues

environment:
  sdk: '>=2.15.1 <3.0.0'


dependencies:
  webcrypto:
    git:
      url: https://github.com/google/webcrypto.dart.git
      ref: cbd72d4

dev_dependencies:
  lints: ^1.0.0
